version: '3.8'

services:
  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tiso-bot
    env_file: .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
    command: >
      sh -c "python /app/create_tables.py && python /app/main.py"
